# Import NUMPY python library

In [2]:
import numpy as np

## Rank 1 Array

In [3]:
arr = np.array([1,2,3,4])

In [5]:
print (arr.shape)
arr[0]

(4,)


1

## Rank 2 Array

In [11]:
arr2 = np.array([[2,2,3],[2,3,5]])
print(arr2.shape)
print("arr2[0,1] = ", arr2[0,1]," and arr[1,2] = ",arr2[1,2])

(2, 3)
arr2[0,1] =  2  and arr[1,2] =  5


## Array filled with Zero's

In [20]:
arrZero = np.zeros((3,3))
arrZero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Array filled with same default value

In [24]:
arrSameOneVal = np.ones((2,4))
arrSameOneVal

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arrSameVal = np.full((2,4),9.25)
arrSameVal

array([[9.25, 9.25, 9.25, 9.25],
       [9.25, 9.25, 9.25, 9.25]])

## Array filled with 1's diagonally rest with 0's

In [29]:
arrOneDiagRestZero = np.eye(3,3)
arrOneDiagRestZero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create an array filled with random values between 0 and 1

In [30]:
arrRandom = np.random.random((3,4))
arrRandom

array([[0.81205665, 0.06953089, 0.39762964, 0.25956224],
       [0.49969576, 0.60793384, 0.88781368, 0.58578137],
       [0.99925726, 0.984846  , 0.51816224, 0.00261965]])

# Array Indexing

## Array Slicing

In [36]:
arr2

array([[2, 2, 3],
       [2, 3, 5]])

In [38]:
arrSlice = arr2[:1,:]
arrSlice

array([[2, 2, 3]])

In [39]:
arrRandom

array([[0.81205665, 0.06953089, 0.39762964, 0.25956224],
       [0.49969576, 0.60793384, 0.88781368, 0.58578137],
       [0.99925726, 0.984846  , 0.51816224, 0.00261965]])

In [41]:
arrSliceRandom = arrRandom[:2, 1:3]
arrSliceRandom

array([[0.06953089, 0.39762964],
       [0.60793384, 0.88781368]])

In [42]:
arrRandom[0,0]

0.8120566521343932

In [43]:
arrSliceRandom[0,0]

0.06953088619906511

In [46]:
arrSlice3 = arrRandom[:, 2:3]
arrSlice3

array([[0.39762964],
       [0.88781368],
       [0.51816224]])

In [47]:
print(arrSlice3.shape)

(3, 1)


In [56]:
arrSlice1D = arrRandom[1,:]
arrSlice1D

array([0.49969576, 0.60793384, 0.88781368, 0.58578137])

In [57]:
arrSlice1D.shape

(4,)

## Modify value of sliced array element and found array element also get modified

In [60]:
arrRandom

array([[0.81205665, 0.06953089, 0.39762964, 0.25956224],
       [0.49969576, 0.60793384, 0.88781368, 0.58578137],
       [0.99925726, 0.984846  , 0.51816224, 0.00261965]])

In [62]:
arrSliceMod = arrRandom[:2,0:2]
arrSliceMod

array([[0.81205665, 0.06953089],
       [0.49969576, 0.60793384]])

In [63]:
arrSliceMod[0,1]

0.06953088619906511

In [64]:
arrSliceMod[0,1] = 99.99
arrRandom

array([[8.12056652e-01, 9.99900000e+01, 3.97629638e-01, 2.59562239e-01],
       [4.99695764e-01, 6.07933843e-01, 8.87813682e-01, 5.85781367e-01],
       [9.99257262e-01, 9.84845999e-01, 5.18162235e-01, 2.61965151e-03]])

In [65]:
arrSliceMod

array([[ 0.81205665, 99.99      ],
       [ 0.49969576,  0.60793384]])

## Copy sliced array into the new array and try to modify value of any element

In [66]:
arrNewSlice = np.array(arrRandom[:2, 1:2])
arrNewSlice

array([[99.99      ],
       [ 0.60793384]])

In [68]:
arrNewSlice[0] = 11.11
arrNewSlice

array([[11.11      ],
       [ 0.60793384]])

In [69]:
arrRandom

array([[8.12056652e-01, 9.99900000e+01, 3.97629638e-01, 2.59562239e-01],
       [4.99695764e-01, 6.07933843e-01, 8.87813682e-01, 5.85781367e-01],
       [9.99257262e-01, 9.84845999e-01, 5.18162235e-01, 2.61965151e-03]])

#### It seems that new array is a copy of sliced array and it won't reference the array so why value only get changed in new array not in the array