# Import NUMPY python library

In [2]:
import numpy as np

## Rank 1 Array

In [3]:
arr = np.array([1,2,3,4])

In [5]:
print (arr.shape)
arr[0]

(4,)


1

## Rank 2 Array

In [11]:
arr2 = np.array([[2,2,3],[2,3,5]])
print(arr2.shape)
print("arr2[0,1] = ", arr2[0,1]," and arr[1,2] = ",arr2[1,2])

(2, 3)
arr2[0,1] =  2  and arr[1,2] =  5


## Array filled with Zero's

In [20]:
arrZero = np.zeros((3,3))
arrZero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Array filled with same default value

In [24]:
arrSameOneVal = np.ones((2,4))
arrSameOneVal

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arrSameVal = np.full((2,4),9.25)
arrSameVal

array([[9.25, 9.25, 9.25, 9.25],
       [9.25, 9.25, 9.25, 9.25]])

## Array filled with 1's diagonally rest with 0's

In [29]:
arrOneDiagRestZero = np.eye(3,3)
arrOneDiagRestZero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create an array filled with random values between 0 and 1

In [30]:
arrRandom = np.random.random((3,4))
arrRandom

array([[0.81205665, 0.06953089, 0.39762964, 0.25956224],
       [0.49969576, 0.60793384, 0.88781368, 0.58578137],
       [0.99925726, 0.984846  , 0.51816224, 0.00261965]])